# Generated by Django 5.1.3 on 2024-12-01 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('reference_number', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone_number', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('detailed_description', models.TextField(null=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_enquires', models.IntegerField(default=0)),
                ('negotiation_percentage', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'property',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('media_url', models.CharField(max_length=255)),
                ('is_image', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('is_document', models.BooleanField(default=False)),
                ('is_leading', models.BooleanField(default=False)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='propertiesapp.property')),
            ],
            options={
                'db_table': 'property_media',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=255, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userprofile',
                'ordering': ['-id'],
            },
        ),
    ]
