# Generated by Django 5.1.3 on 2024-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesapp', '0002_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymedia',
            name='is_leading',
        ),
        migrations.AddField(
            model_name='property',
            name='leading_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
