# Generated by Django 5.1.3 on 2024-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesapp', '0003_remove_propertymedia_is_leading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='negotiation_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
