# Generated by Django 5.1.3 on 2024-12-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesapp', '0004_alter_property_negotiation_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='access_to_roads',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='short_description',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='number_of_enquires',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='negotiation_percentage',
            new_name='distance_from_road',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='max_price',
            new_name='east_west_length',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='min_price',
            new_name='north_south_length',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner_name',
            new_name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='detailed_description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_phone_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_name',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='approval_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='boundary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='encumbrance_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='irrigation_facilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='more_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_ownership',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='soil_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_resource',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
