# Generated by Django 5.1.3 on 2025-01-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertiesapp', '0009_userprofile_created_by_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmlandproperty',
            name='property_type',
            field=models.CharField(default='farmland', max_length=255),
        ),
        migrations.AddField(
            model_name='houseproperty',
            name='property_type',
            field=models.CharField(default='residential', max_length=255),
        ),
        migrations.AddField(
            model_name='plotproperty',
            name='property_type',
            field=models.CharField(default='plots', max_length=255),
        ),
    ]
